### PR TITLE
Add FlatGeobuf and adapt cmdline options

### PR DESCRIPTION
**Pull request by bjornharrtell**
Preliminary work to be able to include FlatGeobuf as a format in the testsuite. That GPKG is very good at the where test was kind of expected. Result from a local run:

```json
{
  "size": {
    "ESRI Shapefile": 3479576609,
    "FlatGeobuf": 2637279240,
    "GPKG": 2830295040
  },
  "metadata": {
    "ESRI Shapefile": 0.08368658499966841,
    "FlatGeobuf": 0.02538551300040126,
    "GPKG": 0.02544921700064151
  },
  "fid": {
    "ESRI Shapefile": 0.09912010799962445,
    "FlatGeobuf": 0.02824044099997991,
    "GPKG": 0.03187913500005379
  },
  "where": {
    "ESRI Shapefile": 18.500975513999947,
    "FlatGeobuf": 15.544728732999829,
    "GPKG": 8.35840021400054
  },
  "spat": {
    "ESRI Shapefile": 6.457024352999724,
    "FlatGeobuf": 0.048738245999629726,
    "GPKG": 0.03436248100024386
  },
  "seq": {
    "ESRI Shapefile": 15.360022124999887,
    "FlatGeobuf": 9.265078321000146,
    "GPKG": 16.460332519000076
  }
}
```

### CODE REVIEW

**Comment by jachym** [comment]
UGH. Now I should run the tests again? 

And you are telling me, you were able to run the "test" of mine on your local setup? You are a hero!

**Review by jachym — APPROVED** [review]

**Comment by bjornharrtell** [comment]
@jachym I was able to but it was not easy :D But yes it was a while ago and should be rerun - I can try and do it again, if you like.

**Comment by jachym** [comment]
you could add it to compare.html as well, right?

**Comment by bjornharrtell** [comment]
@jachym yep, as http://switchfromshapefile.org/#flatgeobuf is now in place I'm definitely motivated to provide an up to date benchmark/comparison.

**Pull request merged**
